# Generated by Django 4.2.4 on 2023-09-04 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comments_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlikes',
            name='who_likes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.author'),
        ),
    ]
