# Generated by Django 4.2.4 on 2023-09-04 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_comments_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentlikes',
            options={'verbose_name': 'Лайки комментариев', 'verbose_name_plural': 'Лайк комментария'},
        ),
    ]
