# Generated by Django 4.2.4 on 2023-09-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_likes_who_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='user_has_liked',
            field=models.BooleanField(default=False),
        ),
    ]
