# Generated by Django 4.2.4 on 2023-09-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_likes_user_has_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='user_has_liked',
        ),
    ]
